spring:
  h2:
    console:
      enabled: true
      path: /h2     # (1) Context path 변경
  datasource:
    url: jdbc:h2:mem:test     # (2) JDBC URL 변경


#  NGINX LOCATION EX) 'http://nginxHost+/static/img/email'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/koronba/Desktop/imgTest/