spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2     # (1) Context path 변경
#  datasource:
#    url: jdbc:h2:mem:test     # (2) JDBC URL 변경
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mainprojectdb.cejscincdeg6.ap-northeast-2.rds.amazonaws.com:3306/twosix?serverTimezone=Asia/Seoul
    username: ${DB_ADMIN_NAME}
    password: ${DB_PASSWORD}

  #  NGINX LOCATION EX) 'http://nginxHost+/static/img/email'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#      location: /Users/koronba/Desktop/imgTest/
  jpa:
    hibernate:
      ddl-auto: update
cloud:
  aws:
    credentials:
      access-key: "AKIAQDPA6GCCGCMCQR7I"
      secret-key: "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"
    s3: #버킷이름
      bucket: fly-to-the-coding
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false
mail:
  address:
    admin: ${ADMIN_ADDRESS}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 360