spring:
  h2:
    console:
      enabled: true
      path: /h2     # (1) Context path 변경
    datasource:
      url: jdbc:h2:mem:test     # (2) JDBC URL 변경
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mainproject.clrdyghz18yc.ap-northeast-2.rds.amazonaws.com:3306/twosix?serverTimezone=Asia/Seoul
#    username: ${DB_ADMIN_NAME}
#    password: ${DB_PASSWORD}

  #  NGINX LOCATION EX) 'http://nginxHost+/static/img/email'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/koronba/Desktop/imgTest/
  jpa:
    hibernate:
      ddl-auto: create

mail:
  address:
    admin: u302@feop.com

jwt:
  secret-key: r98u98ut934ut9438ut9483ut9u34t89u34tu3tu439ut934ut8rguwgusv8sduv9ds
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 360