export const data = [
  {
    id: 1,
    img: 'https://via.placeholder.com/600/92c952',
    price: 3,
    total: 10,
    registered: 5,
    title: '엔트리로 꿀벌 키우기 게임 만들기',
    start: '시작날짜',
    end: '끝날짜',
  },
  {
    id: 2,
    img: 'https://via.placeholder.com/600/92c952',
    price: 3,
    total: 10,
    registered: 5,
    title: '엔트리로 꿀벌 키우기 게임 만들기',
    start: '시작날짜',
    end: '끝날짜',
  },
  {
    id: 3,
    img: 'https://via.placeholder.com/600/92c952',
    price: 3,
    total: 10,
    registered: 5,
    title: '엔트리로 꿀벌 키우기 게임 만들기',
    start: '시작날짜',
    end: '끝날짜',
  },
  {
    id: 4,
    img: 'https://via.placeholder.com/600/92c952',
    price: 3,
    total: 10,
    registered: 5,
    title: '엔트리로 꿀벌 키우기 게임 만들기',
    start: '시작날짜',
    end: '끝날짜',
  },
  {
    id: 5,
    img: 'https://via.placeholder.com/600/92c952',
    price: 3,
    total: 10,
    registered: 5,
    title: '엔트리로 꿀벌 키우기 게임 만들기',
    start: '시작날짜',
    end: '끝날짜',
  },
  {
    id: 6,
    img: 'https://via.placeholder.com/600/92c952',
    price: 3,
    total: 10,
    registered: 5,
    title: '엔트리로 꿀벌 키우기 게임 만들기',
    start: '시작날짜',
    end: '끝날짜',
  },
];
